#language: c

sudo: required
dist: trusty

notifications:
  email: false

before_script:
# travis has changed to 64-bit and we require 32-bit compatibility libraries
  - sudo apt-get update
  - "sudo apt-get install -qq python3-pyqt5 pyqt5-dev pyqt5-dev-tools libreadline6 libreadline6-dev libgtk2.0-dev libgtk-3-dev || true"
  - "sudo apt-get install -qq gcc-arm-none-eabi || true"
  - "sudo apt-get install -qq gcc-arm-linux-gnueabi || true"
  - "sudo apt-get install -qq g++-arm-linux-gnueabi || true"
  - "sudo apt-get install -qq cmake uuid-dev libboost-dev || true"
  - "sudo apt-get install -qq qemu scons nasm || true"
  - "sudo apt-get install -qq libstdc++6:i386 || true"
  - "sudo apt-get install -qq lib32stdc++6 || true"

script:
  - export RELEASE=ascore
  - export BOARD=posix
  - scons > /dev/null
  - export BOARD=versatilepb
  - scons > /dev/null
  - export RELEASE=asboot
  - export BOARD=posix
  - scons > /dev/null
  - export BOARD=versatilepb
  - scons > /dev/null
  - export BOARD=any
  - export ANY=pyas
  - scons > /dev/null
  - cd release/askar
  - python ./ctest.py all
  - export schedfifo=yes && make clean > /dev/null && python ./ctest.py all
  - cd -

env:
  - EMAIL='parai@foxmail.com'

