from building import *

cwd = GetCurrentDir()

Import('asenv')
ASROOT = asenv['ASROOT']

if(IsPlatformWindows()):
    asenv.Append(CPPDEFINES=['__WINDOWS__'])
else:
    asenv.Append(CPPDEFINES=['__LINUX__'])

asenv.Append(CPPDEFINES=['__AS_BY_PARAI__','__AS_CAN_BUS__'])

MODULES = ['LUA_CAN','LUA_SERIAL_CAN','LUA_SOCKET_CAN','DET']

if(asenv['MODULES'] is None):
    asenv['MODULES'] = MODULES
else:
    MODULES = asenv['MODULES']

MODULES.append('ANYOS')

asenv['ARCH'] = 'host'

asenv['BUILD_TYPE'] = 'lib'

objs = []

Return('objs')
