# scons for asboot
import os
import sys
studio=os.path.abspath('../../com/as.tool/config.infrastructure.system/')
sys.path.append(studio)
from building import *

asenv = PrepareEnv()
BOARD = asenv['BOARD']
ASROOT = asenv['ASROOT']

bdir = 'build/%s'%(BOARD)
objs = SConscript('%s/com/SConscript'%(ASROOT),variant_dir=bdir, duplicate=0)

if('flsdrv' in asenv):
    flsdrv = asenv['flsdrv']
    flsobjs = flsdrv['objs']
    flsenv = ForkEnv(asenv, flsdrv)
    target=BOARD+'-flsdrv'
    Building(target,flsobjs,flsenv)
    if('S19' in asenv):
        if(IsPlatformWindows()):target += '.exe'
        action = '%s %s %s-flsdrv.s19'%(asenv['S19'],target,BOARD)
        flsenv.AddPostAction(target,action)

target = BOARD
if(IsPlatformWindows()):target += '.exe'
if('S19' in asenv):
    action = '%s %s %s.s19'%(asenv['S19'],target,BOARD)
    asenv['POSTACTION'].append(action)

Building(BOARD,objs)
