from building import *

cwd = GetCurrentDir()

Import('asenv')
MODULES = asenv['MODULES']

objs = []

AddPackage('https://github.com/autoas/CMSIS_5.git')
AddPackage('https://github.com/autoas/nnom.git')

Return('objs')