import os
from building import *

cwd = GetCurrentDir()

Import('asenv')
arch = asenv['arch']
ASROOT = asenv['ASROOT']
MODULES = asenv['MODULES']

objs = []

objs += Glob('*.c')
objs += Glob('arch/%s/*.c'%(arch))

if(arch == 'arm64'):
	objs += Glob('arch/arm/*.c')

asenv.Append(CPPPATH = ['%s/include'%(cwd),cwd])

Return('objs')
